### ISSUE TITLE
인수테스트와 문서화테스트 환경을 설정한다.

### ISSUE THREAD

**Issue by meatsby** [kascu/kascu-backend#8]
## Description
API 개발 전 ATDD 및 TDD 를 위한 인수테스트 및 문서화테스트 환경을 설정합니다.

## To-do
- [ ] RestDocs 문서화 과정 빌드에 포함
- [ ] WebMvcTest 문서화테스트 환경 구성
- [ ] RestAssured 인수테스트 환경 구성
